"""A video that actually decodes, for the one test that needs one.

The fixture used to write ten bytes of text into a `.MOV`. Everything that only
reads a filename was happy with that -- the extension badge, the shared `?`
panel, the thumbnail placeholder -- and it is exactly enough to make a video
*preview* test meaningless: the element exists, and `play()` on undecodable
bytes never resolves, so "the player was paused on collapse" could be asserted
but never demonstrated. It hung a real browser for thirty seconds instead.

One second of 64x64 colour bars, 2.8 KB, produced once with:

    ffmpeg -f lavfi -i testsrc=size=64x64:rate=10:duration=1 \\
           -pix_fmt yuv420p -movflags +faststart tiny.mp4

Embedded rather than generated when the fixture is built, so the dev harness
does not acquire a hard dependency on ffmpeg being installed to draw a page.
"""

from __future__ import annotations

import base64

TINY_MP4 = base64.b64decode(
    "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAOybW9vdgAAAGxtdmhkAAAAAAAAAA"
    "AAAAAAAAAD6AAAA+gAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAA"
    "AAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAtx0cmFrAAAAXHRraGQAAA"
    "ADAAAAAAAAAAAAAAABAAAAAAAAA+gAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAB"
    "AAAAAAAAAAAAAAAAAABAAAAAAEAAAABAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAPoAA"
    "AIAAABAAAAAAJUbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAoAAAAKABVxAAAAAAALWhkbHIA"
    "AAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAAB/21pbmYAAAAUdm1oZAAAAA"
    "EAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAb9zdGJsAAAA"
    "v3N0c2QAAAAAAAAAAQAAAK9hdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAEAAQABIAAAASA"
    "AAAAAAAAABFUxhdmM2Mi4yOC4xMDIgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAANWF2Y0MBZAAK"
    "/+EAGGdkAAqs2UQmwEQAAAMABAAAAwBQPEiWWAEABmjr48siwP34+AAAAAAQcGFzcAAAAAEAAA"
    "ABAAAAFGJ0cnQAAAAAAAA6cAAAAAAAAAAYc3R0cwAAAAAAAAABAAAACgAABAAAAAAUc3RzcwAA"
    "AAAAAAABAAAAAQAAAGBjdHRzAAAAAAAAAAoAAAABAAAIAAAAAAEAABQAAAAAAQAACAAAAAABAA"
    "AAAAAAAAEAAAQAAAAAAQAAFAAAAAABAAAIAAAAAAEAAAAAAAAAAQAABAAAAAABAAAIAAAAABxz"
    "dHNjAAAAAAAAAAEAAAABAAAACgAAAAEAAAA8c3RzegAAAAAAAAAAAAAACgAABecAAAB7AAAAGA"
    "AAAA0AAAANAAAAYgAAAB0AAAAMAAAADAAAACMAAAAUc3RjbwAAAAAAAAABAAAD4gAAAGJ1ZHRh"
    "AAAAWm1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAALWlsc3QAAA"
    "AlqXRvbwAAAB1kYXRhAAAAAQAAAABMYXZmNjIuMTIuMTAyAAAACGZyZWUAAAdWbWRhdAAAAq4G"
    "Bf//qtxF6b3m2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjUgcjMyMjIgYjM1NjA1YSAtIEguMj"
    "Y0L01QRUctNCBBVkMgY29kZWMgLSBDb3B5bGVmdCAyMDAzLTIwMjUgLSBodHRwOi8vd3d3LnZp"
    "ZGVvbGFuLm9yZy94MjY0Lmh0bWwgLSBvcHRpb25zOiBjYWJhYz0xIHJlZj0zIGRlYmxvY2s9MT"
    "owOjAgYW5hbHlzZT0weDM6MHgxMTMgbWU9aGV4IHN1Ym1lPTcgcHN5PTEgcHN5X3JkPTEuMDA6"
    "MC4wMCBtaXhlZF9yZWY9MSBtZV9yYW5nZT0xNiBjaHJvbWFfbWU9MSB0cmVsbGlzPTEgOHg4ZG"
    "N0PTEgY3FtPTAgZGVhZHpvbmU9MjEsMTEgZmFzdF9wc2tpcD0xIGNocm9tYV9xcF9vZmZzZXQ9"
    "LTIgdGhyZWFkcz0yIGxvb2thaGVhZF90aHJlYWRzPTEgc2xpY2VkX3RocmVhZHM9MCBucj0wIG"
    "RlY2ltYXRlPTEgaW50ZXJsYWNlZD0wIGJsdXJheV9jb21wYXQ9MCBjb25zdHJhaW5lZF9pbnRy"
    "YT0wIGJmcmFtZXM9MyBiX3B5cmFtaWQ9MiBiX2FkYXB0PTEgYl9iaWFzPTAgZGlyZWN0PTEgd2"
    "VpZ2h0Yj0xIG9wZW5fZ29wPTAgd2VpZ2h0cD0yIGtleWludD0yNTAga2V5aW50X21pbj0xMCBz"
    "Y2VuZWN1dD00MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTQwIHJjPWNyZiBtYnRyZW"
    "U9MSBjcmY9MjMuMCBxY29tcD0wLjYwIHFwbWluPTAgcXBtYXg9NjkgcXBzdGVwPTQgaXBfcmF0"
    "aW89MS40MCBhcT0xOjEuMDAAgAAAAzFliIQAn+1zw0px/gtZ2P4Cj4J3NyQ12+nO9F1hxS4Iov"
    "TA89XOIAevd5TA69oZpNSQXmp43qUsLx5J7HnYA15qJoUZOAHjrdOk0CzZt50KKvoHNbILnjz+"
    "bDSbxP8RuUTJAm9s16HdU1iEOtR6X8WElFYgH8y41EVQyiatuYcf+fkzB5slptz0lNcGeMQQau"
    "Kyme9nE4axOA4TW1Af/3tJD5wpVC4gOPGFKFUlJyj0N4ZmNtfFup+3Evs4GTiOeDml3d+wDarp"
    "BA7odpNoTOdSyNK4SwjIAG3o0PJt6o4GLWF13mVJrLxKRfke1DH1fABH4jOtIzqszrGKTmV+L1"
    "soSsEwRHs4dFw1ru2nphIQLC9a5tCRNQdmeFqxreZdgGlXmzzBrCVdXPgEAGAEEMd9cALzEDMT"
    "lQWBU1Nvvp+vV89XR1TvUWfVU1dLCu7Aw+Lm5sCuhkwfNSS6AP7XR6Bdhxmfd8BqNg3P/GABhK"
    "Dsb1Ei+0ig1o7y6r+AOEeTuFxrug2U4ULUcP8G/9uL8oDxyPksNsG86acpx8N52GTkrWVZkLCk"
    "zHr/usEZDCZhxb+1fStp0h41xPrvg0feFV63Med+DaIRw7JWsacCRBYCz8Z/0FuCCrmlO7yDnY"
    "v8Z8eM8esbeE6E8B4xX5SiUuO2Qgs06vwW3+wv5xGsiV0/xdUrvb10v/tsRS5jvnd3M235cyQ+"
    "NErm7WuE1GitAiZAS3zVclPJ8bbYKF1jRTOEsSEsbWzV0ed4KpiUxwpPBR9ett4mF5MPuzltO3"
    "nQ7lccrysND2ODfSJhRdJHKCgcH5jjWlkpvSucLnP9H+SVxGztrpQqLmslxGnpEczSeIm1/+OS"
    "t8GA7dCN6vSvgw6d0Buz5whQAovhv34UM0TTJliguoaDdEdp2o8hmPhFHsxP/XwenbywzdnRR6"
    "36cUF4qZ5fmu8EW6SP38FYjlfLQS7zpqFuyhmsiXQaK91ca49nTLS3FM0dmLfJDW94cNNhcRnv"
    "qoiM2CRMaDj1UfMQqjCaw+X07yD3b05piWYjv88exoj5yHHtszzGdsQNfmf5wopVPJofClTOfj"
    "e+SptKZN4xAAAAd0GaJGxN/w4Dccwy/GEEsmpkWdBe7F2bS43+lvJldxzbupHn4xTS2izt/mIG"
    "NgUD/MXZiHZqmMqAjDRm+PBPvr93obW+/97ORSblbmRsjZEX9DEPc2xBYfn4O7m698m01kGyaR"
    "CyiuD3Zaopq/6fCvrlYsRW4tUcAAAAFEGeQniO/4Kz87ljv29s8/f1KVPZAAAACQGeYXRCX5En"
    "uwAAAAkBnmNqQl93yL0AAABeQZpoSahBaJlMCO8OK1Y0vkvMMGMnt9z+d12ed91ctuYi3+RUb2"
    "XBoykT/Wj6J98JmwEV3ik385kEtCSTytAzQHqPpsqZ67tOTF+0jUFMsMqXcP26UIihuKcEJd9Q"
    "4QAAABlBnoZFESx3Y2fMJodB1Aav56qODNsMQIahAAAACAGepXRCX2DBAAAACAGep2pCX2DAAA"
    "AAH0GaqUmoQWyZTAhL/xdBX/0NHLEECcWbwuwh7KCEfTw="
)
